version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: product_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app-query-net

  pg_admin_service:
    image: dpage/pgadmin4
    container_name: pgadmin_service
    ports:
      - 8085:80
    env_file:
      - .env
    networks:
      - app-query-net
    depends_on:
      - db

networks:
  app-query-net:

volumes:
  postgres_data:
